version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/final_python_app
    exclude:
      - .gitignore

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ec2-user

  BeforeInstall:
    - location: scripts/remove_gitignore.sh
      runas: ec2-user
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user

  ValidateService:
    - location: scripts/validate.sh
      timeout: 300
      runas: ec2-user
